// Code generated by https://github.com/feihua/code_cli
// author：{{author}}
// createTime：{{create_time}}

use rbatis::rbdc::datetime::DateTime;
use serde::{Deserialize, Serialize};

/**
 *{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct {{table_info.class_name}} {
{%- for column in table_info.columns %}
    {%- if column.column_key =="PRI"  %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>
    {%- elif column.is_nullable == "YES"  %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>
    {%- elif column.rust_type == "DateTime"  %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>
    {%- else %}
    pub {{column.rust_name}}: {{column.rust_type}}
    {%- endif %}, //{{column.column_comment}}
{%- endfor %}
}

/**
 *{{table_info.table_comment}}基本操作
 *author：{{author}}
 *date：{{create_time}}
 */
rbatis::crud!({{table_info.class_name}} {},"{{table_info.table_name}}");

/**
 *根据id查询{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
impl_select!({{table_info.class_name}}{select_by_id(id:&i32) -> Option => "`where id = #{id} limit 1`"}, "{{table_info.table_name}}");

/**
 *分页查询{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
impl_select_page!({{table_info.class_name}}{select_page() =>"
     if !sql.contains('count'):
       order by create_time desc"
},"{{table_info.table_name}}");

/**
 *根据条件分页查询{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
impl_select_page!({{table_info.class_name}}{select_page_by_name(name:&str) =>"
     if name != null && name != '':
       where real_name != #{name}
     if name == '':
       where real_name != ''"
},"{{table_info.table_name}}");