[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"
rust-embed = "8.5.0"
heck = "0.5.0"

tera = "1.17.1"

model = { path = "../model", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }