// Code generated by https://github.com/feihua/code_cli
// author：{{author}}
// date：{{create_time}}

use rbatis::rbdc::datetime::DateTime;
use rbatis::plugin::page::PageRequest;
use rbs::to_value;
use salvo::{Request, Response};
use salvo::prelude::*;

use crate::model::{{module_name}}::{{table_info.table_name}}::{ {{table_info.class_name}} };
use crate::RB;
use crate::vo::{{module_name}}::*;
use crate::vo::{{module_name}}::{{table_info.table_name}}_vo::*;

/**
 *添加{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn add_{{table_info.table_name}}(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Add{{table_info.class_name}}Req>().await.unwrap();
    log::info!("add_{{table_info.table_name}} params: {:?}", &item);

    let {{table_info.table_name}} = {{table_info.class_name}} {
    {%- for column in table_info.columns %}
        {%- if column.column_key =="PRI"  %}
        {{column.rust_name}}: None
        {%- elif column.rust_name is containing("create_time") %}
        {{column.rust_name}}: None
        {%- elif column.rust_name is containing("create_by") %}
        {{column.rust_name}}: String::from("")
        {%- elif column.rust_name is containing("update_time") %}
        {{column.rust_name}}: None
        {%- elif column.rust_name is containing("update_by") %}
        {{column.rust_name}}: String::from("")
        {%- else %}
        {{column.rust_name}}: item.{{column.rust_name}}
        {%- endif %}, //{{column.column_comment}}
    {%- endfor %}
    };

    let result = {{table_info.class_name}}::insert(&mut RB.clone(), &{{table_info.table_name}}).await;

    res.render(Json(handle_result(result)))
}

/**
 *删除{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn delete_{{table_info.table_name}}(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Delete{{table_info.class_name}}Req>().await.unwrap();
    log::info!("delete {{table_info.table_name}} params: {:?}", &item);

    let result = {{table_info.class_name}}::delete_in_column(&mut RB.clone(), "id", &item.ids).await;

    res.render(Json(handle_result(result)))
}

/**
 *更新{{table_info.table_comment}}
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn update_{{table_info.table_name}}(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Update{{table_info.class_name}}Req>().await.unwrap();
    log::info!("update_{{table_info.table_name}} params: {:?}", &item);

    let {{table_info.table_name}} = {{table_info.class_name}} {
    {%- for column in table_info.columns %}
        {%- if column.column_key =="PRI"  %}
        {{column.rust_name}}: Some(item.{{column.rust_name}})
        {%- elif column.rust_name is containing("create_time") %}
        {{column.rust_name}}: None
        {%- elif column.rust_name is containing("create_by") %}
        {{column.rust_name}}: String::from("")
        {%- elif column.rust_name is containing("update_time") %}
        {{column.rust_name}}: None
        {%- elif column.rust_name is containing("update_by") %}
        {{column.rust_name}}: String::from("")
        {%- else %}
        {{column.rust_name}}: item.{{column.rust_name}}
        {%- endif %}, //{{column.column_comment}}
    {%- endfor %}

    };

    let result = {{table_info.class_name}}::update_by_column(&mut RB.clone(), &{{table_info.table_name}}, "id").await;

    res.render(Json(handle_result(result)))
}

/**
 *更新{{table_info.table_comment}}状态
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn update_{{table_info.table_name}}_status(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Update{{table_info.class_name}}Req>().await.unwrap();
    log::info!("update_{{table_info.table_name}}_status params: {:?}", &item);

    let rb = &mut RB.clone();
    let param = vec![to_value!(1), to_value!(1)];
    let result = rb.exec("update {{table_info.table_name}} set status = ? where id in ?", param).await;

    res.render(Json(handle_result(result)))
}

/**
 *查询{{table_info.table_comment}}详情
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn query_{{table_info.table_name}}_detail(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Query{{table_info.class_name}}DetailReq>().await.unwrap();
    log::info!("query_{{table_info.table_name}}_detail params: {:?}", &item);

    let result = {{table_info.class_name}}::select_by_id(&mut RB.clone(), &item.id).await;

    match result {
        Ok(d) => {
            let x = d.unwrap();

            let {{table_info.table_name}} = Query{{table_info.class_name}}DetailResp {
            {%- for column in table_info.columns %}
                {%- if column.column_key =="PRI"  %}
                {{column.rust_name}}: x.{{column.rust_name}}.unwrap()
                {%- elif column.is_nullable == "YES"  %}
                {{column.rust_name}}: x.{{column.rust_name}}.unwrap_or_default()
                {%- elif column.rust_type == "DateTime"  %}
                {{column.rust_name}}: x.{{column.rust_name}}.0.to_string()
                {%- else %}
                {{column.rust_name}}: {{column.rust_name}}
                {%- endif %}, //{{column.column_comment}}
            {%- endfor %}

            };

            res.render(Json(ok_result_data({{table_info.table_name}})))
        }
        Err(err) => {
            res.render(Json(ok_result_code(1,err.to_string())))
        }
    }

}

/**
 *查询{{table_info.table_comment}}列表
 *author：{{author}}
 *date：{{create_time}}
 */
#[handler]
pub async fn query_{{table_info.table_name}}_list(req: &mut Request, res: &mut Response) {
    let item = req.parse_json::<Query{{table_info.class_name}}ListReq>().await.unwrap();
    log::info!("query_{{table_info.table_name}}_list params: {:?}", &item);

    let page=&PageRequest::new(item.page_no, item.page_size);
    let result = {{table_info.class_name}}::select_page(&mut RB.clone(), page).await;

    match result {
        Ok(d) => {
            let total = d.total;

            let mut {{table_info.table_name}}_list_data: Vec<{{table_info.class_name}}ListDataResp> = Vec::new();

            for x in d.records {
                let {{table_info.table_name}} = Query{{table_info.class_name}}ListDataResp {
                {%- for column in table_info.columns %}
                    {%- if column.column_key =="PRI"  %}
                    {{column.rust_name}}: x.{{column.rust_name}}.unwrap()
                    {%- elif column.is_nullable == "YES"  %}
                    {{column.rust_name}}: x.{{column.rust_name}}.unwrap_or_default()
                    {%- elif column.rust_type == "DateTime"  %}
                    {{column.rust_name}}: x.{{column.rust_name}}.0.to_string()
                    {%- else %}
                    {{column.rust_name}}: {{column.rust_name}}
                    {%- endif %}, //{{column.column_comment}}
                {%- endfor %}
                };
            }

            res.render(Json(ok_result_page({{table_info.table_name}}_list_data, total)))
        }
        Err(err) => {
            res.render(Json(err_result_page(err.to_string())))
        }
    }

}
