// Code generated by https://github.com/feihua/code_cli
// author：{{author}}
// createTime：{{create_time}}

use serde::{Deserialize, Serialize};

/**
添加{{table_info.table_comment}}请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Add{{table_info.class_name}}Req {
{%- for column in table_info.columns %}
  {%- if column.column_key =="PRI"  %}
  {%- elif column.rust_name is containing("create") %}
  {%- elif column.rust_name is containing("update") %}
  {%- else %}
    {%- if column.is_nullable == "YES"  %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>,//{{column.column_comment}}
    {%- else %}
    pub {{column.rust_name}}: {{column.rust_type}},//{{column.column_comment}}
    {%- endif %}
  {%- endif %}
{%- endfor %}

}

/**
删除{{table_info.table_comment}}请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Delete{{table_info.class_name}}Req {
    pub ids: Vec<i32>,
}

/**
更新{{table_info.table_comment}}请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Update{{table_info.class_name}}Req {
{%- for column in table_info.columns %}
  {%- if column.rust_name is containing("create") %}
  {%- elif column.rust_name is containing("update") %}
  {%- else %}
    {%- if column.is_nullable == "YES"  %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>,//{{column.column_comment}}
    {%- else %}
    pub {{column.rust_name}}: {{column.rust_type}},//{{column.column_comment}}
    {%- endif %}
  {%- endif %}
{%- endfor %}
}

/**
更新{{table_info.table_comment}}状态请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Update{{table_info.class_name}}StatusReq {
    pub ids: Vec<i32>,
    pub status: i32,
}

/**
查询{{table_info.table_comment}}详情请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Query{{table_info.class_name}}DetailReq {
    pub id: i32,
}

/**
查询{{table_info.table_comment}}详情响应参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Query{{table_info.class_name}}DetailResp {
{%- for column in table_info.columns %}
  {%- if column.rust_type =="DateTime"  %}
   pub {{column.rust_name}}: String, //{{column.column_comment}}
  {%- else %}
   pub {{column.rust_name}}: {{column.rust_type}}, //{{column.column_comment}}
  {%- endif %}
{%- endfor %}

}

/**
查询{{table_info.table_comment}}列表请求参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct Query{{table_info.class_name}}ListReq {
    #[serde(rename = "current")]
    pub page_no: u64,
    #[serde(rename = "pageSize")]
    pub page_size: u64,
    {%- for column in table_info.columns %}
    {%- if column.column_key =="PRI"  %}
    {%- elif column.rust_name is containing("create") %}
    {%- elif column.rust_name is containing("update") %}
    {%- elif column.rust_name is containing("remark") %}
    {%- elif column.rust_name is containing("Sort") %}
    {%- elif column.rust_name is containing("sort") %}
    {%- else %}
    pub {{column.rust_name}}: Option<{{column.rust_type}}>,//{{column.column_comment}}
    {%- endif %}
  {%- endfor %}

}

/**
查询{{table_info.table_comment}}列表响应参数
*/
#[derive(Debug, Serialize, Deserialize)]
pub struct {{table_info.class_name}}ListDataResp {
{%- for column in table_info.columns %}
  {%- if column.rust_type =="DateTime"  %}
   pub {{column.rust_name}}: String, //{{column.column_comment}}
  {%- else %}
   pub {{column.rust_name}}: {{column.rust_type}}, //{{column.column_comment}}
  {%- endif %}
{%- endfor %}
}
